# openai
OpenAI_API_KEY: "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"

# Tistory
Tistory_App_ID    : "af74b412dc730076335b39a7a9ea47f1"
Tistory_Secret_Key: "af74b412dc730076335b39a7a9ea47f14ec6cdda8aaa0f04e6d88358b36328b360014498"

# papago API
Papago_ID    : "cfqx7dKPD4MjsIifq9cu"
Papago_Secret: "diHZo53tnM"
